server:
  port: 13100
  address: 0.0.0.0

spring:

  application:
    name: login

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.119.249:12100/db1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: tjdx2024.